### PR TITLE
Check if height is set

### PR DESCRIPTION
**Pull request by schriftgestalt**

### CODE REVIEW

**Comment by anthrotype** [comment]
not sure what you're doing, but in UFO glyphs height is never None, it defaults to 0 (I know that is arguable but I don't think fontMath is the place to fix this)

**Comment by schriftgestalt** [comment]
glyphsLib (or fontMake or whatever) is not setting it correctly in all cases. And I still think it should be able to be None (I know we discussed this).

**Comment by anthrotype** [comment]
both ufoLib2 and defcon defaults height to 0

https://github.com/fonttools/ufoLib2/blob/45597f82b7f2fa8f61748eed0cb29c6fabd07c48/src/ufoLib2/objects/glyph.py#L70
https://github.com/robotools/defcon/blob/32c956cabe3ca6aaeea69ddeaade5c6d0903ae91/Lib/defcon/objects/glyph.py#L123

can you check what type of object are being passed on to MathGlyph?

**Comment by anthrotype** [comment]
that's weird, that line I linked above ensures the height is initialized to 0 if not set. Something else might be setting it to None... glyphsLib?

**Comment by schriftgestalt** [comment]
I’ll dig into this.

**Comment by schriftgestalt** [comment]
I had a messed up ufoLib2. 
it had this:
```
height: Optional[float] = None
```
instead of
```
height: float = 0
```
I think it should be like I had it, but I’m quiet now.

**Pull request closed without merging**
