### PR TITLE
Trying to fix the CI: py.test -> pytest

### PR DESCRIPTION
**Pull request by justvanrossum**

### CODE REVIEW

**Comment by anthrotype** [comment]
I'm still seeing things like https://github.com/robotools/fontMath/actions/runs/3649471028/jobs/6164190348

> Please upload with the Codecov repository upload token to resolve issue.

which reminds me of https://github.com/fonttools/fonttools/issues/2763

I think we can try fix it in the same way

**Comment by anthrotype** [comment]
or we just accept codecov is flaky and make it not fail the whole PR checks

**Comment by anthrotype** [comment]
by which I mean changing this

https://github.com/robotools/fontMath/blob/678c0714d9f8dab1766612ac4c5c5b644b3a51fa/.github/workflows/run-tests.yml#L52

to

> fail_ci_if_error: false

**Comment by benkiel** [comment]
Working on this

**Pull request merged**
